import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";
import { Montserrat } from "next/font/google";
import WebsocketInitializer from "@/components/websocket/websocketInitializer";
import { headers } from "next/headers";
import ConditionalNavbar from "@/components/navbar/ConditionalNavbar";
import { DataProvider } from "@/contexts/dataContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bodyFont = Montserrat({
  subsets: ["latin"],
  weight: ["500", "700"],
});

export const metadata = {
  title: "Social-Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // const headerList = headers();
  // const path = headerList.get("x-invoke-path") || "";
  // const isAuthPage = path.startsWith("/login") || path.startsWith("/sign-up");
  return (
    <html lang="en">
      <body className={`${bodyFont.className}`}>
        <DataProvider>
          <div className="container">
            <WebsocketInitializer />
            {/* {!isAuthPage && <Navbar/>} */}
            <ConditionalNavbar />
            {children}
            <Footer />
          </div>
        </DataProvider>
      </body>
    </html>
  );
}
