import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

import {Montserrat} from "next/font/google";
import WebsocketInitializer from "@/components/websocket/websocketInitializer";

const bodyFont = Montserrat({
  subsets: ['latin'],
  weight: ['500', '700']
});

export const metadata = {
  title: "Social-Network",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const paths = ["/login","/sign-up"]
  // const current = window.location.pathname
  return (
    <html lang="en">
      {/* <body className={`${geistSans.variable} ${geistMono.variable}`}> */}
      <body className={`${bodyFont.className}`}>
        <div className="container">
          {/* <Websocket /> */}
          <WebsocketInitializer />
          {/* {!paths.includes(current) ? : ""} */}
          <Navbar/>
          {children}
          <Footer/>
        </div>
      </body>
    </html>
  );
}
