version: '3.8'

services:
  backend:
    container_name: social-network-backend
    build: ./backend
    ports:
      - "8080:8080"
    working_dir: /backend
    restart: unless-stopped

  frontend:
    container_name: social-network-frontend
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - /frontend/node_modules
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_HOST=http://localhost:8080
    working_dir: /social-network-frontend
    restart: unless-stopped

volumes:
  backend-data:
    name: social-network-backend-data